# Generated by Django 4.2.9 on 2024-06-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="price",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
