# Generated by Django 4.2.9 on 2024-06-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_package_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="balance_amount",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="booking",
            name="total_payment",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
