# Generated by Django 4.2.9 on 2024-06-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_booking_balance_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, null=True
            ),
        ),
    ]
