# Generated by Django 4.2.9 on 2024-07-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_booking_discount_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="ready_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
