# Generated by Django 4.2.9 on 2024-07-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_booking_ready_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=10, null=True
            ),
        ),
    ]
