# Generated by Django 4.2.9 on 2024-07-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_booking_discount_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="advance_payment",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
